services:
    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db

    server:
        build: ./server
        ports:
            - 5051:5000
        command: npm run dev
        volumes:
            - ./server/src/:/app/src/:rw
        environment:
            - CHOKIDAR_USEPOLLING=true

    client:
        build: ./client
        ports:
            - 8081:3000
        command: npm run start
        volumes:
            - ./client/src/:/app/src/:rw
        environment:
            - WDS_SOCKET_HOST=127.0.0.1
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
